# Generated by Django 4.2 on 2026-06-25 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_school_code'),
        ('academics', '0004_examsetup_nationalexamsession_nationalexamcandidate_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'School Admin'), ('teacher', 'Teacher'), ('bursar', 'Bursar'), ('parent', 'Parent / Guardian'), ('support_staff', 'Support Staff'), ('student', 'Student'), ('guardian', 'Guardian'), ('finance', 'Finance Officer')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('job_title', models.CharField(choices=[('teacher', 'Teacher'), ('bursar', 'Bursar'), ('cook', 'Cook'), ('cleaner', 'Cleaner'), ('security', 'Security Guard'), ('driver', 'Driver'), ('librarian', 'Librarian'), ('accountant', 'Accountant'), ('nurse', 'Nurse / Matron'), ('groundskeeper', 'Groundskeeper'), ('other', 'Other')], max_length=20)),
                ('department', models.CharField(choices=[('teaching', 'Teaching'), ('administration', 'Administration'), ('support', 'Support Staff')], max_length=20)),
                ('id_number', models.CharField(blank=True, max_length=20)),
                ('qualifications', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_created', to=settings.AUTH_USER_MODEL)),
                ('subjects_qualified', models.ManyToManyField(blank=True, related_name='qualified_staff', to='academics.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department', 'last_name'],
                'unique_together': {('tenant', 'employee_number')},
            },
        ),
        migrations.CreateModel(
            name='StaffInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('bursar', 'Bursar'), ('admin', 'Admin'), ('support_staff', 'Support Staff')], max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_sent', to=settings.AUTH_USER_MODEL)),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='accounts.staffprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-invited_at'],
            },
        ),
    ]
