# Generated by Django 4.2 on 2026-05-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('domain', models.URLField(unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('motto', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('county', models.CharField(blank=True, max_length=50)),
                ('sub_county', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('primary_color', models.CharField(default='#1a73e8', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7)),
                ('accent_color', models.CharField(default='#fbbc04', max_length=7)),
                ('school_type', models.CharField(choices=[('primary', 'CBC Primary (PP1-Grade 6)'), ('junior_secondary', 'Junior Secondary (Grade 7-9)'), ('senior_secondary', 'Senior Secondary (Grade 10-12)'), ('combined', 'Combined (Primary + Secondary)')], default='combined', max_length=20)),
                ('plan', models.CharField(choices=[('trial', 'Free Trial'), ('starter', 'Starter (up to 400 students)'), ('growth', 'Growth (up to 1000 students)'), ('enterprise', 'Enterprise (Unlimited)')], default='trial', max_length=20)),
                ('trial_ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domain', to='tenants.tenant')),
            ],
        ),
    ]
