# Generated by Django 4.2 on 2026-07-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_school_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='attendance_auto_lock_days',
            field=models.PositiveIntegerField(default=2, help_text='Number of days after which attendance sessions are auto-locked. 0 = disabled.'),
        ),
    ]
