# Generated by Django 4.2 on 2026-05-09 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_update_student_status_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='staff_parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'bursar', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_children', to=settings.AUTH_USER_MODEL),
        ),
    ]
