# Generated by Django 4.2 on 2026-07-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_school_code'),
        ('students', '0003_student_staff_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
