import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Download } from 'lucide-react'
import { academicsApi } from '@/api/academics'
import { studentsApi } from '@/api/students'
import { useAuthStore } from '@/store/authStore'
import { Avatar, Button, Card, PageHeader, Spinner } from '@/components/ui'
import { LevelBadge, StatusBadge, listFromResponse, openBlobInNewTab, termLabel } from './shared'

function InfoRow({ label, value }) {
  return <div className="flex justify-between border-b border-gray-50 py-2 text-sm"><span className="text-gray-500">{label}</span><span className="font-medium text-gray-900">{value || '—'}</span></div>
}

export default function ReportCardDetailPage() {
  const { id } = useParams()
  const navigate = useNavigate()
  const isAdmin = useAuthStore(state => state.hasRole('admin', 'superadmin'))
  const [card, setCard] = useState(null)
  const [student, setStudent] = useState(null)
  const [grades, setGrades] = useState({})
  const [activities, setActivities] = useState([])
  const [examResults, setExamResults] = useState([])
  const [loading, setLoading] = useState(true)

  const fetchCard = useCallback(async () => {
    setLoading(true)
    try {
      const { data } = await academicsApi.getReportCard(id)
      setCard(data)
      const [studentRes, gradesRes, activitiesRes, examRes] = await Promise.all([
        studentsApi.getStudent(data.student),
        academicsApi.getStudentReport({ student: data.student, term: data.term, academic_year: data.academic_year }),
        academicsApi.getCoCurricular({ student: data.student, term: data.term, academic_year: data.academic_year }),
        academicsApi.getStudentResults({
          student: data.student,
          term: data.report_type === 'termly' ? data.term : undefined,
          academic_year: data.academic_year,
        }),
      ])
      setStudent(studentRes.data)
      setGrades(gradesRes.data || {})
      setActivities(activitiesRes.data?.results || activitiesRes.data || [])
      setExamResults(listFromResponse(examRes.data))
    } finally {
      setLoading(false)
    }
  }, [id])

  useEffect(() => { fetchCard() }, [fetchCard])

  const pdf = async () => {
    const { data } = await academicsApi.getReportCardPdf(id)
    openBlobInNewTab(data)
  }
  const publish = async () => {
    await academicsApi.publishReportCard(id)
    fetchCard()
  }

  const examGroups = useMemo(() => {
    const groups = new Map()
    examResults.forEach(result => {
      const key = `${result.exam_name}-${result.exam_term}-${result.exam_academic_year}`
      if (!groups.has(key)) {
        const term = result.exam_term ? termLabel(result.exam_term) : 'Term'
        groups.set(key, {
          title: `${result.exam_name} - ${term} ${result.exam_academic_year}`,
          results: [],
        })
      }
      groups.get(key).results.push(result)
    })
    return Array.from(groups.values())
  }, [examResults])

  if (loading) return <div className="flex justify-center py-20"><Spinner className="h-7 w-7" /></div>
  if (!card) return null

  return (
    <div className="space-y-6">
      <button onClick={() => navigate('/academics/report-cards')} className="flex items-center gap-1 text-sm text-gray-500 hover:text-gray-900"><ArrowLeft size={15} /> Back to Report Cards</button>
      <PageHeader
        title={`${card.student_name} - ${card.classroom_name} - ${termLabel(card.term)}`}
        description={<StatusBadge status={card.status} />}
        action={<div className="flex gap-2"><Button variant="secondary" onClick={pdf} className="gap-2"><Download size={16} /> Download PDF</Button>{isAdmin && card.status !== 'published' && <Button onClick={publish}>Publish</Button>}</div>}
      />
      <div className="grid grid-cols-1 xl:grid-cols-[280px_1fr_320px] gap-5">
        <Card className="p-5">
          <div className="mb-4 flex items-center gap-3">
            <Avatar name={card.student_name} photo={student?.photo} size="lg" />
            <div><p className="font-semibold text-gray-900">{card.student_name}</p><p className="text-xs text-gray-500">{card.admission_number}</p></div>
          </div>
          <InfoRow label="Class" value={card.classroom_name} />
          <InfoRow label="Term" value={termLabel(card.term)} />
          <InfoRow label="Year" value={card.academic_year} />
          <InfoRow label="Report Type" value={card.report_type} />
          <InfoRow label="Generated By" value={card.generated_by_name} />
        </Card>

        <Card className="p-5">
          <h2 className="mb-4 font-semibold text-gray-900">CBC Grades</h2>
          <div className="space-y-5">
            {Object.entries(grades).map(([subjectName, subject]) => (
              <div key={subjectName}>
                <h3 className="font-semibold text-gray-900">{subjectName}</h3>
                <div className="mt-3 space-y-3">
                  {Object.entries(subject.strands || {}).map(([strandName, strand]) => (
                    <div key={strandName} className="rounded-lg border border-gray-100 p-3">
                      <p className="text-sm font-medium text-gray-800">{strandName}</p>
                      {Object.entries(strand.sub_strands || {}).map(([subName, sub]) => (
                        <div key={subName} className="mt-3">
                          <p className="text-xs font-semibold uppercase text-gray-400">{subName}</p>
                          <div className="mt-2 space-y-2">
                            {(sub.outcomes || []).map(outcome => (
                              <div key={outcome.outcome_id} className="flex items-start justify-between gap-3 rounded-lg bg-gray-50 p-3 text-sm">
                                <div><p className="text-gray-700">{outcome.description}</p>{outcome.remarks && <p className="mt-1 text-xs text-gray-500">{outcome.remarks}</p>}</div>
                                <LevelBadge level={outcome.level} />
                              </div>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </Card>

        <Card className="p-5">
          <h2 className="mb-4 font-semibold text-gray-900">Exam Results</h2>
          {examGroups.length === 0 ? (
            <p className="text-sm text-gray-400">No exam results recorded.</p>
          ) : (
            <div className="space-y-5">
              {examGroups.map(group => (
                <div key={group.title} className="rounded-lg border border-gray-100">
                  <div className="border-b border-gray-100 px-4 py-2 text-sm font-semibold text-gray-900">{group.title}</div>
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="border-b border-gray-50 text-xs uppercase text-gray-500">
                          <th className="px-4 py-2 text-left">Subject</th>
                          <th className="px-4 py-2 text-left">Marks</th>
                          <th className="px-4 py-2 text-left">%</th>
                          <th className="px-4 py-2 text-left">Level</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-50">
                        {group.results.map(result => (
                          <tr key={result.id}>
                            <td className="px-4 py-2">{result.subject_name}</td>
                            <td className="px-4 py-2">{result.marks ?? '-'} / {result.total_marks ?? '-'}</td>
                            <td className="px-4 py-2">{result.marks == null ? '-' : Number(result.percentage || 0).toFixed(1)}</td>
                            <td className="px-4 py-2"><LevelBadge level={result.cbc_level} /></td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              ))}
            </div>
          )}
        </Card>

        <div className="space-y-5">
          <Card className="p-5">
            <h2 className="mb-3 font-semibold text-gray-900">Attendance</h2>
            <InfoRow label="Days Open" value={card.days_school_open} />
            <InfoRow label="Present" value={card.days_present} />
            <InfoRow label="Absent" value={card.days_absent} />
            <InfoRow label="Late" value={card.days_late} />
            <div className="mt-3 h-2 rounded-full bg-gray-100"><div className="h-2 rounded-full bg-green-600" style={{ width: `${Math.min(card.attendance_percentage || 0, 100)}%` }} /></div>
            <p className="mt-1 text-right text-sm font-medium text-gray-900">{card.attendance_percentage || 0}%</p>
          </Card>
          <Card className="p-5"><h2 className="mb-3 font-semibold text-gray-900">Conduct</h2>{['discipline', 'respect', 'responsibility', 'punctuality', 'participation'].map(item => <InfoRow key={item} label={item[0].toUpperCase() + item.slice(1)} value={card[`conduct_${item}`]} />)}</Card>
          <Card className="p-5"><h2 className="mb-3 font-semibold text-gray-900">Co-curricular</h2>{activities.length ? activities.map(a => <InfoRow key={a.id} label={a.activity_name} value={`${a.rating || '—'} ${a.remarks || ''}`} />) : <p className="text-sm text-gray-400">No activities recorded.</p>}</Card>
          <Card className="p-5"><h2 className="mb-3 font-semibold text-gray-900">Remarks</h2><InfoRow label="Teacher" value={card.class_teacher_remarks} /><InfoRow label="Principal" value={card.principal_remarks} /></Card>
          <Card className="p-5"><h2 className="mb-3 font-semibold text-gray-900">Dates</h2><InfoRow label="Closing" value={card.closing_date} /><InfoRow label="Next Opening" value={card.next_term_opening_date} /></Card>
        </div>
      </div>
    </div>
  )
}
