import api from './client'

export const timetablingApi = {
  getReadiness: (params) => api.get('/timetabling/readiness/', { params }),
  getScheduleTemplates: (params) => api.get('/timetabling/schedule-templates/', { params }),
  createScheduleTemplate: (data) => api.post('/timetabling/schedule-templates/', data),
  updateScheduleTemplate: (id, data) => api.patch(`/timetabling/schedule-templates/${id}/`, data),
  deleteScheduleTemplate: (id) => api.delete(`/timetabling/schedule-templates/${id}/`),
  getPeriods: (params) => api.get('/timetabling/periods/', { params }),
  createPeriod: (data) => api.post('/timetabling/periods/', data),
  updatePeriod: (id, data) => api.patch(`/timetabling/periods/${id}/`, data),
  deletePeriod: (id) => api.delete(`/timetabling/periods/${id}/`),
  getRooms: (params) => api.get('/timetabling/rooms/', { params }),
  createRoom: (data) => api.post('/timetabling/rooms/', data),
  updateRoom: (id, data) => api.patch(`/timetabling/rooms/${id}/`, data),
  deleteRoom: (id) => api.delete(`/timetabling/rooms/${id}/`),
  getSubjectRules: (params) => api.get('/timetabling/subject-rules/', { params }),
  createSubjectRule: (data) => api.post('/timetabling/subject-rules/', data),
  updateSubjectRule: (id, data) => api.patch(`/timetabling/subject-rules/${id}/`, data),
  bulkUpsertSubjectRules: (data) => api.post('/timetabling/subject-rules/bulk-upsert/', { rules: data }),
  getTeacherAssignments: (params) => api.get('/timetabling/teacher-subject-assignments/', { params }),
  createTeacherAssignment: (data) => api.post('/timetabling/teacher-subject-assignments/', data),
  bulkTeacherAssignment: (data) => api.post('/timetabling/teacher-subject-assignments/bulk/', data),
  getJobs: (params) => api.get('/timetabling/jobs/', { params }),
  createJob: (data) => api.post('/timetabling/jobs/', data),
  bulkUpdatePeriods: (data) => api.post('/timetabling/periods/bulk-update/', data),
  getJob: (id) => api.get(`/timetabling/jobs/${id}/`),
  regeneratePartial: (id, classStreamIds) => api.post(`/timetabling/jobs/${id}/regenerate-partial/`, { class_stream_ids: classStreamIds }),
  getEntries: (params, { skipErrorToast = false } = {}) => api.get('/timetabling/entries/', { params, skipErrorToast }),
  getMyClasses: () => api.get('/timetabling/entries/my-classes/'),
  updateEntry: (id, data) => api.patch(`/timetabling/entries/${id}/`, data),
  lockEntry: (id, locked) => api.post(`/timetabling/entries/${id}/lock/`, { locked }),
  publishJob: (id) => api.post(`/timetabling/jobs/${id}/publish/`),
  createEntry: (data) => api.post('/timetabling/entries/', data),
  copyFromTerm: (data) => api.post('/timetabling/jobs/copy-from-term/', data),
  downloadTimetablePdf: (params) => api.get('/timetabling/pdf/', { params, responseType: 'blob' }),
}