# Generated by Django 4.2 on 2026-05-28 20:26

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0002_add_school_code'),
        ('students', '0003_student_staff_parent'),
        ('academics', '0003_rebuild_cbc_academics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('opener', 'Opener Exam'), ('midterm', 'Mid-Term Exam'), ('endterm', 'End Term Exam'), ('mock', 'Mock Exam'), ('other', 'Other')], max_length=10)),
                ('term', models.CharField(choices=[('term1', 'Term 1'), ('term2', 'Term 2'), ('term3', 'Term 3')], max_length=10)),
                ('academic_year', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_setups', to='students.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-academic_year', '-start_date'],
                'unique_together': {('tenant', 'name', 'classroom', 'term', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='NationalExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('KNAT', 'Grade 3 National Assessment (KNAT)'), ('KPAT', 'Grade 6 Performance Assessment (KPAT)'), ('KJSAT', 'Grade 9 Junior School Assessment (KJSAT)')], max_length=10)),
                ('academic_year', models.PositiveIntegerField()),
                ('centre_number', models.CharField(blank=True, max_length=20)),
                ('centre_name', models.CharField(blank=True, max_length=200)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('is_results_entered', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_exam_sessions', to='students.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='national_exam_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'name', 'classroom', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='NationalExamCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(blank=True, max_length=20)),
                ('is_registered', models.BooleanField(default=False)),
                ('registration_confirmed', models.BooleanField(default=False)),
                ('special_needs', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='academics.nationalexamsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_exam_candidates', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='academics.examsetup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_subjects', to='academics.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_subjects_teaching', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'unique_together': {('exam', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamCBCSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('records_synced', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_syncs', to='academics.examsetup')),
                ('synced_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbc_syncs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='NationalExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('grade', models.CharField(blank=True, choices=[('EE', 'Exceeding Expectation'), ('ME', 'Meeting Expectation'), ('AE', 'Approaching Expectation'), ('BE', 'Below Expectation')], max_length=2)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.nationalexamcandidate')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='national_results', to='academics.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'candidate', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cbc_level', models.CharField(choices=[('EE', 'Exceeding Expectation'), ('ME', 'Meeting Expectation'), ('AE', 'Approaching Expectation'), ('BE', 'Below Expectation')], max_length=2)),
                ('is_overridden', models.BooleanField(default=False)),
                ('override_reason', models.CharField(blank=True, max_length=200)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_results_entered', to=settings.AUTH_USER_MODEL)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.examsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'exam_subject', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('be_min', models.PositiveIntegerField(default=0)),
                ('be_max', models.PositiveIntegerField(default=29)),
                ('ae_min', models.PositiveIntegerField(default=30)),
                ('ae_max', models.PositiveIntegerField(default=49)),
                ('me_min', models.PositiveIntegerField(default=50)),
                ('me_max', models.PositiveIntegerField(default=74)),
                ('ee_min', models.PositiveIntegerField(default=75)),
                ('ee_max', models.PositiveIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant',)},
            },
        ),
    ]
