# Generated by Django 4.2 on 2026-07-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_examsetup_nationalexamsession_nationalexamcandidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='auto_marked',
            field=models.BooleanField(default=False, help_text='True if this session was created by the auto-mark system.'),
        ),
        migrations.AlterField(
            model_name='nationalexamsession',
            name='name',
            field=models.CharField(choices=[('KEYA', 'KEYA (Kenya Early Years Assessment) – Grade 3'), ('KPSEA', 'KPSEA (Kenya Primary School Education Assessment) – Grade 6'), ('KJSEA', 'KJSEA (Kenya Junior School Education Assessment) – Grade 9')], max_length=10),
        ),
    ]
