# Generated by Django 4.2 on 2026-07-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_timetablepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='curriculum_phase',
            field=models.CharField(choices=[('pp', 'Pre-Primary'), ('lower_primary', 'Lower Primary (Grade 1-3)'), ('upper_primary', 'Upper Primary (Grade 4-6)'), ('jss', 'Junior Secondary (Grade 7-9)'), ('sss', 'Senior Secondary (Grade 10-12)'), ('all', 'All Levels')], default='all', help_text='Which grade band this subject is designed for.', max_length=20),
        ),
    ]
