# Generated by Django 4.2 on 2026-07-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_add_school_code'),
        ('students', '0003_student_staff_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('school_summary', 'School Summary'), ('class_performance', 'Class Performance'), ('early_warning', 'Early Warning'), ('subject_comparison', 'Subject Comparison')], max_length=30)),
                ('term', models.CharField(blank=True, max_length=10)),
                ('academic_year', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='students.classroom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['tenant', 'snapshot_type', 'academic_year'], name='analytics_a_tenant__3d42d6_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['tenant', 'classroom', 'term', 'academic_year'], name='analytics_a_tenant__87d62e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticssnapshot',
            unique_together={('tenant', 'snapshot_type', 'classroom', 'term', 'academic_year')},
        ),
    ]
