# Generated by Django 4.2 on 2026-06-29 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0002_add_school_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('student_admitted', 'Student Admitted'), ('student_transferred', 'Student Transferred'), ('student_graduated', 'Student Graduated'), ('student_dropped', 'Student Dropped'), ('student_promoted', 'Student Promoted'), ('staff_invited', 'Staff Invited'), ('staff_joined', 'Staff Joined'), ('staff_deactivated', 'Staff Deactivated'), ('staff_reactivated', 'Staff Reactivated'), ('fee_paid', 'Fee Paid'), ('invoice_generated', 'Invoice Generated'), ('invoice_bulk_generated', 'Bulk Invoices Generated'), ('waiver_approved', 'Waiver Approved'), ('waiver_applied', 'Waiver Applied'), ('receipt_issued', 'Receipt Issued'), ('announcement_sent', 'Announcement Sent'), ('announcement_scheduled', 'Announcement Scheduled'), ('message_sent', 'Message Sent'), ('exam_created', 'Exam Created'), ('exam_results_published', 'Exam Results Published'), ('report_card_generated', 'Report Card Generated'), ('report_card_published', 'Report Card Published'), ('attendance_marked', 'Attendance Marked'), ('grade_entered', 'Grade Entered'), ('timetable_uploaded', 'Timetable Uploaded'), ('login', 'User Login'), ('logout', 'User Logout'), ('settings_updated', 'Settings Updated')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_model', models.CharField(blank=True, help_text="Django model label, e.g. 'students.Student'", max_length=100)),
                ('target_id', models.CharField(blank=True, help_text='Target object UUID or PK', max_length=100)),
                ('target_name', models.CharField(blank=True, help_text='Human readable target name', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_system', models.BooleanField(default=False, help_text='True for automated/system actions')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['tenant', '-created_at'], name='activity_ac_tenant__0c4418_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['tenant', 'activity_type', '-created_at'], name='activity_ac_tenant__be953f_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['tenant', 'actor', '-created_at'], name='activity_ac_tenant__2b8e91_idx'),
        ),
    ]
