import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assert_old_finance_tables_are_empty(apps, schema_editor):
    """This development rebuild must never drop real finance records."""
    table_names = [
        'finance_feestructure',
        'finance_payment',
        'finance_mpesatransaction',
    ]
    with schema_editor.connection.cursor() as cursor:
        for table_name in table_names:
            cursor.execute(
                """
                SELECT EXISTS (
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_schema = current_schema()
                      AND table_name = %s
                )
                """,
                [table_name],
            )
            if not cursor.fetchone()[0]:
                continue

            cursor.execute(f'SELECT COUNT(*) FROM "{table_name}"')
            if cursor.fetchone()[0]:
                raise RuntimeError(
                    f'Cannot rebuild finance schema because {table_name} contains data.'
                )


CREATE_NEW_FINANCE_TABLES = """
DROP TABLE IF EXISTS "finance_receipt" CASCADE;
DROP TABLE IF EXISTS "finance_studentfee" CASCADE;
DROP TABLE IF EXISTS "finance_mpesatransaction" CASCADE;
DROP TABLE IF EXISTS "finance_payment" CASCADE;
DROP TABLE IF EXISTS "finance_feestructure" CASCADE;

CREATE TABLE "finance_feestructure" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "term" varchar(20) NOT NULL,
    "academic_year" varchar(9) NOT NULL,
    "base_amount" numeric(12, 2) NOT NULL,
    "late_penalty_amount" numeric(12, 2) NOT NULL,
    "late_penalty_days" integer NOT NULL CHECK ("late_penalty_days" >= 0),
    "is_active" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "classroom_id" bigint NOT NULL REFERENCES "students_classroom" ("id") DEFERRABLE INITIALLY DEFERRED,
    "tenant_id" bigint NOT NULL REFERENCES "tenants_tenant" ("id") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "finance_feestructure_tenant_class_term_year_uniq"
        UNIQUE ("tenant_id", "classroom_id", "term", "academic_year")
);
CREATE INDEX "finance_feestructure_classroom_id_idx" ON "finance_feestructure" ("classroom_id");
CREATE INDEX "finance_feestructure_tenant_id_idx" ON "finance_feestructure" ("tenant_id");

CREATE TABLE "finance_studentfee" (
    "id" uuid NOT NULL PRIMARY KEY,
    "expected_amount" numeric(12, 2) NOT NULL,
    "waived_amount" numeric(12, 2) NOT NULL,
    "carried_forward" numeric(12, 2) NOT NULL,
    "penalty_amount" numeric(12, 2) NOT NULL,
    "status" varchar(20) NOT NULL,
    "due_date" date NOT NULL,
    "paid_amount" numeric(12, 2) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "fee_structure_id" bigint NOT NULL REFERENCES "finance_feestructure" ("id") DEFERRABLE INITIALLY DEFERRED,
    "student_id" bigint NOT NULL REFERENCES "students_student" ("id") DEFERRABLE INITIALLY DEFERRED,
    "tenant_id" bigint NOT NULL REFERENCES "tenants_tenant" ("id") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "finance_studentfee_student_structure_uniq" UNIQUE ("student_id", "fee_structure_id")
);
CREATE INDEX "finance_studentfee_fee_structure_id_idx" ON "finance_studentfee" ("fee_structure_id");
CREATE INDEX "finance_studentfee_student_id_idx" ON "finance_studentfee" ("student_id");
CREATE INDEX "finance_studentfee_tenant_id_idx" ON "finance_studentfee" ("tenant_id");

CREATE TABLE "finance_payment" (
    "id" uuid NOT NULL PRIMARY KEY,
    "amount" numeric(12, 2) NOT NULL,
    "payment_method" varchar(20) NOT NULL,
    "status" varchar(20) NOT NULL,
    "mpesa_receipt_number" varchar(50) NOT NULL,
    "mpesa_checkout_request_id" varchar(100) NOT NULL,
    "mpesa_transaction_date" timestamp with time zone NULL,
    "idempotency_key" varchar(100) NOT NULL UNIQUE,
    "notes" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "recorded_by_id" bigint NULL REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED,
    "student_fee_id" uuid NULL REFERENCES "finance_studentfee" ("id") DEFERRABLE INITIALLY DEFERRED,
    "student_id" bigint NOT NULL REFERENCES "students_student" ("id") DEFERRABLE INITIALLY DEFERRED,
    "tenant_id" bigint NOT NULL REFERENCES "tenants_tenant" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX "finance_payment_recorded_by_id_idx" ON "finance_payment" ("recorded_by_id");
CREATE INDEX "finance_payment_student_fee_id_idx" ON "finance_payment" ("student_fee_id");
CREATE INDEX "finance_payment_student_id_idx" ON "finance_payment" ("student_id");
CREATE INDEX "finance_payment_tenant_id_idx" ON "finance_payment" ("tenant_id");
CREATE INDEX "finance_pay_status_25feb1_idx" ON "finance_payment" ("status", "tenant_id");
CREATE INDEX "finance_pay_student_237141_idx" ON "finance_payment" ("student_id", "status");

CREATE TABLE "finance_receipt" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "receipt_number" varchar(50) NOT NULL UNIQUE,
    "amount" numeric(12, 2) NOT NULL,
    "payment_method" varchar(20) NOT NULL,
    "term" varchar(20) NOT NULL,
    "academic_year" varchar(9) NOT NULL,
    "issued_at" timestamp with time zone NOT NULL,
    "issued_by_id" bigint NULL REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED,
    "payment_id" uuid NOT NULL UNIQUE REFERENCES "finance_payment" ("id") DEFERRABLE INITIALLY DEFERRED,
    "student_id" bigint NOT NULL REFERENCES "students_student" ("id") DEFERRABLE INITIALLY DEFERRED,
    "tenant_id" bigint NOT NULL REFERENCES "tenants_tenant" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX "finance_receipt_issued_by_id_idx" ON "finance_receipt" ("issued_by_id");
CREATE INDEX "finance_receipt_student_id_idx" ON "finance_receipt" ("student_id");
CREATE INDEX "finance_receipt_tenant_id_idx" ON "finance_receipt" ("tenant_id");
"""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(assert_old_finance_tables_are_empty, migrations.RunPython.noop),
                migrations.RunSQL(CREATE_NEW_FINANCE_TABLES, reverse_sql=migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.DeleteModel(name='MPesaTransaction'),
                migrations.DeleteModel(name='Payment'),
                migrations.DeleteModel(name='FeeStructure'),
                migrations.CreateModel(
                    name='FeeStructure',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('term', models.CharField(choices=[('term1', 'Term 1'), ('term2', 'Term 2'), ('term3', 'Term 3'), ('annual', 'Annual')], max_length=20)),
                        ('academic_year', models.CharField(max_length=9)),
                        ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('late_penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('late_penalty_days', models.PositiveIntegerField(default=0, help_text='Grace period in days before penalty applies')),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='students.classroom')),
                        ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='tenants.tenant')),
                    ],
                    options={
                        'ordering': ['-academic_year', 'term'],
                        'unique_together': {('tenant', 'classroom', 'term', 'academic_year')},
                    },
                ),
                migrations.CreateModel(
                    name='StudentFee',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('waived_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('carried_forward', models.DecimalField(decimal_places=2, default=0, help_text='Arrears rolled from previous term', max_digits=12)),
                        ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='unpaid', max_length=20)),
                        ('due_date', models.DateField()),
                        ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.feestructure')),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student')),
                        ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                    ],
                    options={
                        'ordering': ['-fee_structure__academic_year', 'fee_structure__term'],
                        'unique_together': {('student', 'fee_structure')},
                    },
                ),
                migrations.CreateModel(
                    name='Payment',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Card')], max_length=20)),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                        ('mpesa_receipt_number', models.CharField(blank=True, max_length=50)),
                        ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=100)),
                        ('mpesa_transaction_date', models.DateTimeField(blank=True, null=True)),
                        ('idempotency_key', models.CharField(db_index=True, help_text='Prevents double-processing of callbacks', max_length=100, unique=True)),
                        ('notes', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student')),
                        ('student_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.studentfee')),
                        ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                    ],
                    options={
                        'ordering': ['-created_at'],
                        'indexes': [models.Index(fields=['status', 'tenant'], name='finance_pay_status_25feb1_idx'), models.Index(fields=['student', 'status'], name='finance_pay_student_237141_idx')],
                    },
                ),
                migrations.CreateModel(
                    name='Receipt',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('payment_method', models.CharField(max_length=20)),
                        ('term', models.CharField(max_length=20)),
                        ('academic_year', models.CharField(max_length=9)),
                        ('issued_at', models.DateTimeField(auto_now_add=True)),
                        ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                        ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='finance.payment')),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                        ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                    ],
                    options={
                        'ordering': ['-issued_at'],
                    },
                ),
            ],
        ),
    ]
