# Generated by Django 4.2 on 2026-05-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_add_manual_payment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired'), ('reversed', 'Reversed'), ('bounced', 'Bounced')], default='pending', max_length=20),
        ),
    ]
