# Generated by Django 4.2 on 2026-05-09 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_staff_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0002_add_school_code'),
        ('finance', '0006_studentfee_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='waiver_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='WaiverPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('full_waiver', 'Full Waiver'), ('staff_child', 'Staff Child'), ('bursary', 'Government Bursary'), ('sibling', 'Sibling Discount'), ('sponsor', 'Sponsor Support'), ('partial', 'Partial Waiver'), ('orphan', 'Orphan')], max_length=50)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=50)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_waiver_policies', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_policies', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'category')},
            },
        ),
        migrations.CreateModel(
            name='StudentWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_on', models.DateField(auto_now_add=True)),
                ('valid_from_term', models.CharField(choices=[('term1', 'Term 1'), ('term2', 'Term 2'), ('term3', 'Term 3'), ('annual', 'Annual')], max_length=10)),
                ('valid_from_year', models.IntegerField()),
                ('valid_until_term', models.CharField(blank=True, choices=[('term1', 'Term 1'), ('term2', 'Term 2'), ('term3', 'Term 3'), ('annual', 'Annual')], max_length=10)),
                ('valid_until_year', models.IntegerField(blank=True, null=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='waiver_docs/')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_waivers', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_waivers', to='finance.waiverpolicy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_waivers', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'policy')},
            },
        ),
        migrations.AddField(
            model_name='studentfee',
            name='waiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.studentwaiver'),
        ),
    ]
