# Generated by Django 4.2 on 2026-07-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_school_code'),
        ('finance', '0007_studentfee_waiver_reason_waiverpolicy_studentwaiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('stk_push', 'STK Push'), ('callback', 'M-Pesa Callback'), ('status_query', 'Status Query'), ('expire', 'Auto Expire'), ('reconcile', 'Reconcile'), ('callback_orphan', 'Orphan Callback')], max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result_code', models.CharField(blank=True, max_length=10)),
                ('result_desc', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_merchant_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Normalized phone number used for STK push', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='system_notes',
            field=models.TextField(blank=True, help_text='Internal processing notes'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(db_index=True, help_text='Prevents double-processing of callbacks', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('tenant', 'idempotency_key')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'mpesa_checkout_request_id'], name='finance_pay_tenant__33932f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'mpesa_receipt_number'], name='finance_pay_tenant__6ec9b5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['tenant', 'student', 'status'], name='finance_stu_tenant__d16ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['tenant', 'due_date'], name='finance_stu_tenant__4ee323_idx'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['checkout_request_id', 'event_type'], name='finance_pay_checkou_9ed683_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['tenant', 'created_at'], name='finance_pay_tenant__e2a1e5_idx'),
        ),
    ]
