# Generated by Django 4.2 on 2026-07-09 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_school_code'),
        ('finance', '0008_paymentlog_payment_failed_at_payment_failure_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.studentfee'),
        ),
        migrations.CreateModel(
            name='ReceiptCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_counter', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
