"""Academics serializers package — re-exports all serializers for backwards compatibility."""
from .curriculum import (
    ClassSubjectAssignmentSerializer,
    LearningOutcomeSerializer,
    StrandSerializer,
    SubjectListSerializer,
    SubjectSerializer,
    SubStrandSerializer,
)
from .grades import (
    BulkExamResultSerializer,
    BulkGradeSerializer,
    CBCGradeSerializer,
    ExamCBCSyncSerializer,
    ExamConfigSerializer,
    ExamResultImportSerializer,
    ExamResultSerializer,
    ExamSetupListSerializer,
    ExamSetupSerializer,
    ExamSubjectSerializer,
    GradeImportSerializer,
)
from .national_exams import (
    NationalExamCandidateSerializer,
    NationalExamResultSerializer,
    NationalExamSessionSerializer,
)
from .school_life import (
    AttendanceRecordSerializer,
    AttendanceSessionListSerializer,
    AttendanceSessionSerializer,
    ClassTimetableSerializer,
    CoCurricularActivitySerializer,
    GenerateReportCardSerializer,
    MarkAttendanceSerializer,
    ReportCardSerializer,
    StudentCoCurricularSerializer,
)

__all__ = [
    'AttendanceRecordSerializer',
    'AttendanceSessionListSerializer',
    'AttendanceSessionSerializer',
    'BulkExamResultSerializer',
    'BulkGradeSerializer',
    'CBCGradeSerializer',
    'ClassSubjectAssignmentSerializer',
    'ClassTimetableSerializer',
    'CoCurricularActivitySerializer',
    'ExamCBCSyncSerializer',
    'ExamConfigSerializer',
    'ExamResultImportSerializer',
    'ExamResultSerializer',
    'ExamSetupListSerializer',
    'ExamSetupSerializer',
    'ExamSubjectSerializer',
    'GenerateReportCardSerializer',
    'GradeImportSerializer',
    'LearningOutcomeSerializer',
    'MarkAttendanceSerializer',
    'NationalExamCandidateSerializer',
    'NationalExamResultSerializer',
    'NationalExamSessionSerializer',
    'ReportCardSerializer',
    'StrandSerializer',
    'StudentCoCurricularSerializer',
    'SubjectListSerializer',
    'SubjectSerializer',
    'SubStrandSerializer',
]